version: "3"

services:
  app:
    build:
      context: .
    ports:
    - "80:5000"
    volumes:
    - .app

#  db:
#    image: mongo:3.0.2
  mongodb:
    image: mongo:4.2.3
    ports:
      - '27017:27017'
#    command: >
#      sh -c "python manage.py runserver "